int $number
$number = 2; // = is assignment operator. Right to left, giving 2 to number
print ($numebr);

string $name
$name = "david";
print ($name)

float $price = 29.99;
print ($price);

float $position[] = {-4.5, -2.2, 0.1, 3.3};

print ($position[3]);

//Maya doesnt have booleans, but would look like:
// bool $passingGrade


/*
    int (integer/whole number): 1, 15, -200
    float (float/decimal): 3.14
    string (text): "word", "phrase with words"
    bool (boolean - true/false): 1 or 0
    array (container of multiple values): [1, 24, 52], ["word1", "word2"] (needs to stay same data type)
*/
